[tool.poetry]
name = "Kart"
version = "0.5.2"
description = "A very flexible static site generator written in python"
authors = ["Giacomo Caironi <giacomo.caironi@gmail.com>"]
license = "MIT"
readme = 'README.md'
include = ["kart_quickstart/**/*"]
exclude = ['kart_quickstart/_site/**/*']

[tool.poetry.dependencies]
python = "^3.8"
jinja2 = "^2.11"
pyyaml = '^5.1'
"paka.cmark" = '^2.2'
python-frontmatter = '^0.5'
feedgen = '^0.9'
livereload = "^2.6"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
